roles:
  - name: geerlingguy.docker
    version: 7.0.1
  - name: jason_riddle.tailscale
    version: 1.1.22
collections:
  - name: https://github.com/kencx/ansible-collection.git
    type: git
    version: HEAD
  - name: community.docker
